-- =====================================================
-- FINSIGHT-AI Database Table Structures
-- =====================================================
-- This file contains all CREATE statements for the database tables
-- =====================================================

-- =====================================================
-- 1. FLOWAI_USERS Table
-- =====================================================
CREATE TABLE FLOWAI_USERS (
    NTID VARCHAR2(50) PRIMARY KEY,
    EMAIL VARCHAR2(100) NOT NULL,
    ACCOUNT VARCHAR2(100),
    ACCOUNT_ID NUMBER,
    PASSWORD VARCHAR2(255),
    ROLE VARCHAR2(20) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT UK_USER_EMAIL UNIQUE (EMAIL),
    CONSTRAINT CHK_USER_ROLE CHECK (ROLE IN ('USER', 'DEVELOPER', 'MANAGER', 'SCRUM_MASTER', 'ADMIN'))
);

CREATE INDEX IDX_USERS_EMAIL ON FLOWAI_USERS(EMAIL);
CREATE INDEX IDX_USERS_ACCOUNT_ID ON FLOWAI_USERS(ACCOUNT_ID);
CREATE INDEX IDX_USERS_ROLE ON FLOWAI_USERS(ROLE);
CREATE INDEX IDX_USERS_ACTIVE ON FLOWAI_USERS(ACTIVE);

-- =====================================================
-- 2. FLOWAI_ACCOUNTS Table
-- =====================================================
CREATE TABLE FLOWAI_ACCOUNTS (
    ACCOUNT_ID NUMBER PRIMARY KEY,
    ACCOUNT_NAME VARCHAR2(100) NOT NULL UNIQUE,
    CREATED_AT TIMESTAMP NOT NULL,
    ACTIVE NUMBER(1) DEFAULT 1 NOT NULL
);

CREATE INDEX IDX_ACCOUNTS_NAME ON FLOWAI_ACCOUNTS(ACCOUNT_NAME);
CREATE INDEX IDX_ACCOUNTS_ACTIVE ON FLOWAI_ACCOUNTS(ACTIVE);

-- =====================================================
-- 3. FLOWAI_REQUESTS Table
-- =====================================================
CREATE SEQUENCE FLOWAI_REQUESTS_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE FLOWAI_REQUESTS (
    REQUEST_ID NUMBER PRIMARY KEY,
    TITLE VARCHAR2(200) NOT NULL,
    DESCRIPTION CLOB,
    REQUEST_TYPE VARCHAR2(50) NOT NULL,
    PRIORITY VARCHAR2(20) NOT NULL,
    STATUS VARCHAR2(20) NOT NULL,
    CREATED_BY VARCHAR2(50) NOT NULL,
    ASSIGNED_TO VARCHAR2(50),
    ACCOUNT_ID NUMBER,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    ASSIGNED_AT TIMESTAMP,
    ASSIGNED_BY VARCHAR2(50),
    ETA TIMESTAMP,
    ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_REQUEST_CREATED_BY FOREIGN KEY (CREATED_BY) REFERENCES FLOWAI_USERS(NTID),
    CONSTRAINT FK_REQUEST_ASSIGNED_TO FOREIGN KEY (ASSIGNED_TO) REFERENCES FLOWAI_USERS(NTID),
    CONSTRAINT FK_REQUEST_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES FLOWAI_ACCOUNTS(ACCOUNT_ID),
    CONSTRAINT CHK_REQUEST_TYPE CHECK (REQUEST_TYPE IN ('ADHOC', 'BUG', 'FEATURE', 'ENHANCEMENT')),
    CONSTRAINT CHK_REQUEST_PRIORITY CHECK (PRIORITY IN ('LOW', 'MEDIUM', 'HIGH', 'URGENT')),
    CONSTRAINT CHK_REQUEST_STATUS CHECK (STATUS IN ('OPEN', 'ASSIGNED', 'IN_PROGRESS', 'ON_HOLD', 'DELAYED', 'COMPLETED', 'CANCELLED'))
);

CREATE OR REPLACE TRIGGER FLOWAI_REQUESTS_TRG
BEFORE INSERT ON FLOWAI_REQUESTS
FOR EACH ROW
BEGIN
    IF :NEW.REQUEST_ID IS NULL THEN
        SELECT FLOWAI_REQUESTS_SEQ.NEXTVAL INTO :NEW.REQUEST_ID FROM DUAL;
    END IF;
END;
/

CREATE INDEX IDX_REQUESTS_CREATED_BY ON FLOWAI_REQUESTS(CREATED_BY);
CREATE INDEX IDX_REQUESTS_ASSIGNED_TO ON FLOWAI_REQUESTS(ASSIGNED_TO);
CREATE INDEX IDX_REQUESTS_ACCOUNT_ID ON FLOWAI_REQUESTS(ACCOUNT_ID);
CREATE INDEX IDX_REQUESTS_STATUS ON FLOWAI_REQUESTS(STATUS);
CREATE INDEX IDX_REQUESTS_PRIORITY ON FLOWAI_REQUESTS(PRIORITY);
CREATE INDEX IDX_REQUESTS_REQUEST_TYPE ON FLOWAI_REQUESTS(REQUEST_TYPE);
CREATE INDEX IDX_REQUESTS_ACTIVE ON FLOWAI_REQUESTS(ACTIVE);
CREATE INDEX IDX_REQUESTS_ETA ON FLOWAI_REQUESTS(ETA);
CREATE INDEX IDX_REQUESTS_CREATED_AT ON FLOWAI_REQUESTS(CREATED_AT);

-- =====================================================
-- 4. FLOWAI_USER_ACCOUNTS Table (Junction Table)
-- =====================================================
CREATE SEQUENCE FLOWAI_USER_ACCOUNTS_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE FLOWAI_USER_ACCOUNTS (
    USER_ACCOUNT_ID NUMBER PRIMARY KEY,
    NTID VARCHAR2(50) NOT NULL,
    ACCOUNT_ID NUMBER NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_USER_ACCOUNT_USER FOREIGN KEY (NTID) REFERENCES FLOWAI_USERS(NTID),
    CONSTRAINT FK_USER_ACCOUNT_ACCOUNT FOREIGN KEY (ACCOUNT_ID) REFERENCES FLOWAI_ACCOUNTS(ACCOUNT_ID),
    CONSTRAINT UK_USER_ACCOUNT UNIQUE (NTID, ACCOUNT_ID)
);

CREATE OR REPLACE TRIGGER FLOWAI_USER_ACCOUNTS_TRG
BEFORE INSERT ON FLOWAI_USER_ACCOUNTS
FOR EACH ROW
BEGIN
    IF :NEW.USER_ACCOUNT_ID IS NULL THEN
        SELECT FLOWAI_USER_ACCOUNTS_SEQ.NEXTVAL INTO :NEW.USER_ACCOUNT_ID FROM DUAL;
    END IF;
END;
/

CREATE INDEX IDX_USER_ACCOUNTS_NTID ON FLOWAI_USER_ACCOUNTS(NTID);
CREATE INDEX IDX_USER_ACCOUNTS_ACCOUNT ON FLOWAI_USER_ACCOUNTS(ACCOUNT_ID);
CREATE INDEX IDX_USER_ACCOUNTS_ACTIVE ON FLOWAI_USER_ACCOUNTS(ACTIVE);

-- =====================================================
-- 5. FLOWAI_REQUEST_COMMENTS Table (NEW - For Comments)
-- =====================================================
CREATE SEQUENCE FLOWAI_REQUEST_COMMENTS_SEQ START WITH 1 INCREMENT BY 1;

CREATE TABLE FLOWAI_REQUEST_COMMENTS (
    COMMENT_ID NUMBER PRIMARY KEY,
    REQUEST_ID NUMBER NOT NULL,
    COMMENT_TEXT CLOB NOT NULL,
    COMMENTED_BY VARCHAR2(50) NOT NULL,
    COMMENTED_AT TIMESTAMP NOT NULL,
    IS_ETA_CHANGE NUMBER(1) DEFAULT 0 NOT NULL,
    OLD_ETA TIMESTAMP,
    NEW_ETA TIMESTAMP,
    CHANGE_REASON VARCHAR2(500),
    ACTIVE NUMBER(1) DEFAULT 1 NOT NULL,
    CONSTRAINT FK_COMMENT_REQUEST FOREIGN KEY (REQUEST_ID) REFERENCES FLOWAI_REQUESTS(REQUEST_ID) ON DELETE CASCADE,
    CONSTRAINT FK_COMMENT_USER FOREIGN KEY (COMMENTED_BY) REFERENCES FLOWAI_USERS(NTID)
);

CREATE OR REPLACE TRIGGER FLOWAI_REQUEST_COMMENTS_TRG
BEFORE INSERT ON FLOWAI_REQUEST_COMMENTS
FOR EACH ROW
BEGIN
    IF :NEW.COMMENT_ID IS NULL THEN
        SELECT FLOWAI_REQUEST_COMMENTS_SEQ.NEXTVAL INTO :NEW.COMMENT_ID FROM DUAL;
    END IF;
    IF :NEW.COMMENTED_AT IS NULL THEN
        :NEW.COMMENTED_AT := SYSTIMESTAMP;
    END IF;
END;
/

CREATE INDEX IDX_COMMENTS_REQUEST_ID ON FLOWAI_REQUEST_COMMENTS(REQUEST_ID);
CREATE INDEX IDX_COMMENTS_COMMENTED_BY ON FLOWAI_REQUEST_COMMENTS(COMMENTED_BY);
CREATE INDEX IDX_COMMENTS_COMMENTED_AT ON FLOWAI_REQUEST_COMMENTS(COMMENTED_AT);
CREATE INDEX IDX_COMMENTS_ETA_CHANGE ON FLOWAI_REQUEST_COMMENTS(IS_ETA_CHANGE);
CREATE INDEX IDX_COMMENTS_ACTIVE ON FLOWAI_REQUEST_COMMENTS(ACTIVE);

-- =====================================================
-- End of Table Structures
-- =====================================================
